server:
  port: 8882
spring:
  application:
    name: blah-oauth

  datasource:
    url: jdbc:mysql://${MYSQL_ADDR}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver