server:
  port: 8801
spring:
  application:
    name: blah-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8801/blah-oauth/oauth/rsa/getPublicKey'  #RSA公钥
  redis:
    database: 0
    port: 6379
    host: ${REDIS_ADDR}
    password:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes: #配置路由路径
        - id: blah-api
          uri: lb://blah-api
          predicates:
            - Path=/blah-api/**
          filters:
            - StripPrefix=1
        - id: blah-oauth
          uri: lb://blah-oauth
          predicates:
            - Path=/blah-oauth/**
          filters:
            - StripPrefix=1
blah:
  whitelist:
    urls:
      - "/**/*.ico"
      - "/blah-oauth/oauth/token"
      - "/blah-oauth/oauth/rsa/getPublicKey"