##
spring:
  datasource:
    url: jdbc:mysql://192.168.230.128:3306/blah_user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 192.168.230.128
    port: 6379

feign:
  okhttp:
    enabled: true


