version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
      TZ: Asia/Shanghai
      MYSQL_DATABASE: nacos_devtest
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
    ports:
      - 3306:3306
    volumes:
      - /mydata/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /mydata/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /mydata/mysql/log:/var/log/mysql #日志文件挂载
  redis:
    image: redis:5
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
  #  nginx:
  #    image: nginx:1.10
  #    container_name: nginx
  #    volumes:
  #      - /mydata/nginx/conf:/etc/nginx #配置文件挂载
  #      - /mydata/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
  #      - /mydata/nginx/log:/var/log/nginx #日志文件挂载
  #    ports:
  #      - 80:80
  #  rabbitmq:
  #    image: rabbitmq:3.7.15-management
  #    container_name: rabbitmq
  #    volumes:
  #      - /mydata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
  #      - /mydata/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
  #    ports:
  #      - 5672:5672
  #      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    user: root
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.6.2
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  #  mongo:
  #    image: mongo:4.2.5
  #    container_name: mongo
  #    volumes:
  #      - /mydata/mongo/db:/data/db #数据文件挂载
  #    ports:
  #      - 27017:27017
  nacos-registry:
    image: nacos/nacos-server:1.3.2
    container_name: nacos
    volumes:
      - /mydata/nacos/standalone-logs/:/home/nacos/logs
      - /mydata/nacos/custom.properties:/home/nacos/init.d/custom.properties
    environment:
      - "PREFER_HOST_MODE=hostname"
      - "MODE=standalone"
      - "SPRING_DATASOURCE_PLATFORM=mysql"
      - "MYSQL_SERVICE_HOST=mysql"
      - "MYSQL_SERVICE_DB_NAME=nacos_devtest"
      - "MYSQL_SERVICE_PORT=3306"
      - "MYSQL_SERVICE_USER=nacos"
      - "MYSQL_SERVICE_PASSWORD=nacos"
      - "MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false"
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555
    depends_on:
      - mysql

  zipkin:
    image: openzipkin/zipkin:2.23.2
    environment:
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch
      # Uncomment to see requests to and from elasticsearch
      # - ES_HTTP_LOGGING=BODY
    ports:
      - 9411:9411
    depends_on:
      - elasticsearch

